services:

  n8n-app:
    image: docker.io/nfrastack/n8n:latest
    container_name: n8n-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`n8n.example.com`)
      - traefik.http.services.n8n.loadbalancer.server.port=80
    environment:
      - TIMEZONE=America/Vancouver

      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password

      - GENERIC_TIMEZONE=America/Vancouver
      - WEBHOOK_TUNNEL_URL=http://n8n.example.com/
      - VUE_APP_URL_BASE_API=http://n8n.example.com/

      - ENABLE_NGINX=FALSE

      - N8N_PROTOCOL=https
      - N8N_HOST=n8n.example.com
      - N8N_PORT=80
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
